name: py2
dependencies:
  - python==2.7.13
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - h5py
  - pip:
    - opencv_python
    - seaborn
    - pillow==4.3.0
    - tensorflow_gpu==1.3.0
    - keras==2.0.8
    - pydot_ng
    - nvidia-ml-py
    - tqdm
