name: py3
dependencies:
    - python==3.5.2
    - numpy==1.12.1
    - matplotlib==2.0.1
    - jupyter==1.0.0
    - opencv
    - pillow
    - scikit-learn==0.18.1
    - scikit-image==0.13.0
    - scipy==0.19.0
    - h5py==2.7.0
    - seaborn==0.7.1
    - pandas==0.20.1
    - pip:
        - tensorflow_gpu==1.1.0
        - keras==2.0.4
        - pydot==1.2.3
        - graphviz==0.7.1
        - simpleitk==1.0.0
        - cairocffi==0.8.0
        - captcha==0.2.2
        - editdistance==0.3.1
        - tqdm
